# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='active',
        ),
        migrations.AddField(
            model_name='exchange',
            name='activated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='webapp.PersonGroup'),
        ),
    ]
