# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160911_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persongroup',
            name='members',
            field=models.ManyToManyField(related_name='person_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
