# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160911_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftlist',
            old_name='list',
            new_name='gift_list',
        ),
        migrations.AlterField(
            model_name='draw',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='webapp.Exchange'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draw',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftlist',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_lists', to='webapp.Exchange'),
        ),
        migrations.AlterField(
            model_name='giftlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
